const path = require("path");
const autoprefixer = require("autoprefixer"); // webpack config uses Node JS so it uses require syntax etc

module.exports = {
  devtool: "cheap-module-eval-source-map", // configs the type of sources maps generated, this is best
  entry: "./src/index.html", // where the app should be loaded from
  output: {
    path: "",
    filename: "bundle.js",
    publicPath: path.resolve(__dirname, "dist")
  }, // the build output
  resolve: { extensions: [".js", ".jsx"] }, // the file extensions to build
  module: {
    rules: [
      { test: /\.js$/, loader: "babel-loader", exclude: /node_modules/ }, // what to do for js files, what loader to use what to exclude from build
      {
        test: /\.css$/, // what to do for css files, what loaders to use what to exclude from build
        use: [
          { loader: "style-loader" }, // order of loaders is bottom to top and matters
          {
            loader: "css-loader",
            options: {
              importLoaders: 1, // Lets css-loader know one loader is run before it e.g. postcss-loader
              modules: true, // enables css modules
              localIdentName: "[name]__[local]__[hash:base64:5]" //configs for the classnames generated by css modules
            }
          },
          {
            loader: "postcss-loader",
            options: {
              ident: "postcss",
              plugins: () => [
                autoprefixer({ browsers: ["> 1%", "last 2 versions"] }) // will create auto prefixs for css so it works on all browsers
              ]
            }
          }
        ],
        exclude: /node_modules/
      }
    ]
  }
};
